# Generated by Django 5.1.1 on 2024-10-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="username",
            field=models.CharField(default="1", max_length=255),
        ),
    ]
