# Generated by Django 5.1.1 on 2024-11-13 23:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content_type',
            new_name='contentType',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='FQID',
        ),
        migrations.RemoveField(
            model_name='post',
            name='FQID',
        ),
        migrations.AddField(
            model_name='comment',
            name='contentType',
            field=models.CharField(default='text/markdown', max_length=32),
        ),
        migrations.AddField(
            model_name='comment',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='post',
            name='page',
            field=models.URLField(default='page/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.CharField(default='comment', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False, unique=True),
        ),
    ]
