# Generated by Django 5.1.1 on 2024-10-20 06:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_like_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="FQID",
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="post",
            name="FQID",
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="post",
            name="page",
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
