# Generated by Django 5.1.1 on 2024-10-17 03:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
