# Generated by Django 5.1.1 on 2024-10-17 03:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_like_like_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
