# Generated by Django 5.1.1 on 2024-10-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='post',
            new_name='shared_post',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('shared_post', 'Shared Post'), ('follow', 'Follow Request'), ('like', 'Like'), ('comment', 'Comment')], max_length=11),
        ),
    ]
