# Generated by Django 5.1.1 on 2024-10-18 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_rename_post_notification_shared_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='shared_post',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='like',
        ),
    ]
