# Generated by Django 5.1.1 on 2024-11-13 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Node',
        ),
    ]
