# Generated by Django 4.2.10 on 2024-10-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.URLField(primary_key=True, serialize=False)),
                ('host', models.URLField()),
                ('display_name', models.CharField(max_length=100)),
                ('github', models.URLField(blank=True, null=True)),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('page', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
