# Generated by Django 5.1.1 on 2024-11-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='isNode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='author',
            name='isTrustedNode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='author',
            name='type',
            field=models.CharField(choices=[('author', 'Author'), ('node', 'Node')], default='author', max_length=10),
        ),
    ]
