# Generated by Django 5.1.1 on 2024-11-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='isNode',
            field=models.BooleanField(default=False),
        ),
    ]
