# Generated by Django 5.1.1 on 2024-11-14 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_author_isnode_author_istrustednode_author_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='isTrustedNode',
            new_name='isSharedNode',
        ),
    ]
