# Generated by Django 5.1.1 on 2024-10-20 02:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("author", "0002_author_followers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="followers",
        ),
    ]
