# Generated by Django 5.1.1 on 2024-10-20 06:55

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("author", "0002_author_followers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="followers",
        ),
        migrations.AddField(
            model_name="author",
            name="FQID",
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="following",
            name="like_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="following",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("accepted", "Accepted")],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="page",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="following",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
