# Generated by Django 5.1.1 on 2024-11-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_author_isnode'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='type',
            field=models.CharField(choices=[('author', 'Author'), ('node', 'Node')], default='author', max_length=10),
        ),
    ]
