# Generated by Django 5.1.1 on 2024-11-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_author_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
