# Generated by Django 4.2.10 on 2024-10-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_alter_author_host_alter_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.CharField(max_length=255),
        ),
    ]
